apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: backstage
      app.kubernetes.io/name: backstage
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: backstage
        app.kubernetes.io/name: backstage
    spec:
      containers:
      - command:
        - node
        - packages/backend
        - --config
        - /config/app-config.yaml
        env:
        - name: POSTGRES_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: databasePassword
              name: backstage-postgresql
        - name: POSTGRES_HOST
          value: backstage-postgresql.{{ $.Release.Namespace }}.svc
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: APP_CONFIG_catalog_providers_keycloakOrg_default_baseUrl
          value: {{ $.Values.keycloak.baseUrl }}
        - name: APP_CONFIG_catalog_providers_keycloakOrg_default_loginRealm
          value: {{ $.Values.keycloak.loginRealm }}
        - name: APP_CONFIG_catalog_providers_keycloakOrg_default_realm
          value: {{ $.Values.keycloak.realm }}
        - name: APP_CONFIG_catalog_providers_keycloakOrg_default_clientId
          valueFrom:
            secretKeyRef:
              key: rhsso.clientId
              name: backstage-keycloak-creds
        - name: APP_CONFIG_catalog_providers_keycloakOrg_default_clientSecret
          valueFrom:
            secretKeyRef:
              key: rhsso.clientSecret
              name: backstage-keycloak-creds
        - name: LOG_LEVEL
          value: debug
        image: {{ $.Values.image }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: backstage
        ports:
        - containerPort: 7007
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: backstage-config
          readOnly: true
      - args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=http://localhost:7007
        - --http-address=0.0.0.0:4180
        - --skip-provider-button
        - --insecure-oidc-allow-unverified-email=true
        env:
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: {{ $.Values.oauth2Proxy.issuerUrl }}
        - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
          value: "{{ $.Values.oauth2Proxy.skipTlsVerify }}"
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: rhsso.clientId
              name: backstage-keycloak-creds
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: rhsso.clientSecret
              name: backstage-keycloak-creds
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth.cookieSecret
              name: backstage-keycloak-creds
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: janus-dev-oauth-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccount: backstage
      serviceAccountName: backstage
      volumes:
      - name: backstage-config
        secret:
          defaultMode: 420
          secretName: backstage-config
