apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: backstage-bucket-claim
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  generateBucketName: backstage-bucket-
  storageClassName: openshift-storage.noobaa.io